<a href="https://colab.research.google.com/github/shashismg/machine_learning/blob/main/linear_reg_single_var.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("home_prices.csv")
df.head()

area_sqr_ft  price_lakhs
0          656         39.0
1         1260         83.2
2         1057         86.6
3         1259         59.0
4         1800        140.0

In [3]:
df[['area_sqr_ft']]

area_sqr_ft
0           656
1          1260
2          1057
3          1259
4          1800
5          1325
6          1085
7          1110
8          1700
9           960
10         1800
11          700

In [4]:
df[['area_sqr_ft']].head()

area_sqr_ft
0          656
1         1260
2         1057
3         1259
4         1800

In [5]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(df[["area_sqr_ft"]], df['price_lakhs'])

LinearRegression()

In [ ]:
'''
as data size is smaller it taken few seconds.
usually in real world project data size will be big and takes some time
'''

In [6]:
model.predict([[1500]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([95.56913434])

In [7]:
model.predict([[1500], [700]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([95.56913434, 54.22372995])

In [8]:
model.coef_, model.intercept_

(array([0.05168176]), np.float64(18.046501102723433))

In [9]:
model.coef_[0] * 1500 + model.intercept_

np.float64(95.56913433756426)